### ISSUE TITLE
What id did-common-dotnet

### ISSUE THREAD

**Issue by nembal** [decentralized-identity/did-common-dotnet#2]
Hi, 

Please make a short intro to what is this work-item and what WG will manage it.  (use a repo topic like "wg-id" or "wg-cc"

Or maybe it was meant to be did-comm-dotnet?

**Comment by veikkoeeva** [comment]
Sorry, no one seem to have noticed this.

I do not know which WG to attribute this to. Can you help?

The plan is to create a .NET implementation of DIDs and VCs (and presentations, it looks like), we're currently spiking a design and along it a potential implementation direction. At leas I am, see at https://github.com/decentralized-identity/did-common-dotnet/tree/veikkoeeva/initial-spike.

**Comment by nembal** [comment]
@peacekeeper - I would assume it might be under your oversight. (also, potentially @csuwildcat can help too) 
Can you collaborate with @veikkoeeva on his question?

**Comment by peacekeeper** [comment]
@nembal my understanding is that this is intended to become a generic implementation of DIDs and DID documents in .net, similiar to the did-common-java library: https://github.com/decentralized-identity/did-common-java.

I already added the "wg-id" tag a while ago when I originally created the repo. It's also listed as a work item on the WG's main repo:

- https://github.com/decentralized-identity/identifiers-discovery/

We talked about this during the WG calls and there was agreement to add this work item:

- https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#meeting---14-dec-2020---1400-et-recording
- https://github.com/decentralized-identity/identifiers-discovery/blob/main/agenda.md#meeting---21-dec-2020---1400-et-recording

Maybe one problem is that all the work seems to be happening on different branches. @veikkoeeva it may be helpful to commit something to the main branch, if it's just an initial README with some description of the repo?

**Comment by peacekeeper** [comment]
@nembal see https://github.com/decentralized-identity/did-common-dotnet/pull/3

**Comment by veikkoeeva** [comment]
@peacekeeper That PR looks good to me.

The plan with my branch has been to check that with this approach it's possible:
- To use another cryptograhic providers besides BouncyCastle. I think it's fairly sure with this approach (it should be refactored, but I record concerns as issues later).
- That it's possible to consume various DIDs. It seems to. Even the deprecated EBSI ones seem to work.
- It's possible to create VCs with the same idea. Likely, but nothing there yet.
- It's possible to create presentations (for exhange) with these strong types. Looks like possible.

Yes, so a generic implementation. With a quick glance the strongly typed approach is not too different from the Rust one at https://sprucesystems.medium.com/announcing-decentralized-identity-on-tezos-4bf266a7af3f. I have not wanted to put anything to main in case someone has another approach in mind plus that I have wanted to see if taking this route is fruitful.

I have a few other deadlines coming in the next few weeks but intend to pick up some pace already this month and especially when this month is over.

**Comment by veikkoeeva** [comment]
@peacekeeper I took the liberty to marge the the PR and close this.

Anyone reading this, do re-open or create new ones if there is something, anything, to ask. If more chat like interface is preferable and if the volumes won't become too high, I'm available in DIF Slack (do ping) and maybe also via Nethereum Discord or MS Orleans Gitter where I frequent.

**Comment by juanfranblanco** [comment]
From a common perspective the spike https://github.com/decentralized-identity/did-common-dotnet/tree/did-url-parser covers these areas https://github.com/decentralized-identity/did-common-java/blob/main/src/main/java/foundation/identity/did/DIDURL.java and the parser element https://github.com/decentralized-identity/did-common-java/tree/main/src/main/java/foundation/identity/did/parser

**Comment by veikkoeeva** [comment]
For the record, in my spike I plan to use https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0 (see examples) and have function names to the operations according to the spec with URL links.

Thanks for putting those links here @juanfranblanco. I think I go quickly to see if Java version has specific named functions or arrangements that would align well.

**Comment by juanfranblanco** [comment]
The Java version uses https://github.com/decentralized-identity/did-common-java/blob/main/src/main/resources/did.abnf to generate the parser that is valid with the spec. The javascript version uses the regex, I followed the regex version with unit tests for this as it was a simpler alternative. I don't know how system.uri will help here as it uses a complete different syntax from this spec, but it may be able to get extended hijacked.

**Comment by juanfranblanco** [comment]
I think we can start moving away from spikes now, mainly to validate solutions and start moving into an architecture, I know this may be much bigger than common but if is something functional (and a valid foundation) it may lead to others add more stuff.

Edit: even foundational areas can be later on refactor / redesign internally if they are decoupled enough.

**Comment by veikkoeeva** [comment]
[DID syntax specification](https://www.w3.org/TR/did-core/#did-syntax) tells it conforms to [RFC3986](https://www.w3.org/TR/did-core/#bib-rfc3986) (see at https://tools.ietf.org/html/rfc3986). So one idea could be to use .NET Uri to parse the examples like from https://www.w3.org/TR/did-core/#example-7

```
var uri = new Uri("did:example:123?service=agent&relativeRef=/credentials#degree");
var degreeFragment = uri.Fragment; //Should contain "#degree".
```
This way the URIs can be handled in familiar ways and DID specification specific rules, processing etc. applied to them while otherwise they are kept in `strings` (or as `Uri`s). Maybe has security and performance implications besides developer familiarity and coordination efforts between language specific implementations.

Likely wrapped into functions with protocol specific names and in comments links to specification to aid any developer to understand why URIs are processed in specific ways.
